{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
stringData:
  {{ .Values.postgresql.passwordKey }}: {{ .Values.postgresql.password | quote }}
{{- end }}
