apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-db.fullname" . }}
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    {{- include "postgres-db.labels" . | nindent 4 }}
